### ISSUE TITLE
More labels if not use „inverter on/off“ and „charger on/off“

### ISSUE THREAD

**Issue by testpaul999** [roblatour/ESP32RemoteForVictron#3]
**Is your feature request related to a problem? Please describe.**

More labels if not use „inverter on/off“ and „charger on/off“

**Describe the solution you'd like**

my wish are this as one idea 
![image01](https://github.com/roblatour/ESP32RemoteForVictron/assets/35597907/48ae7b6e-cdf9-466b-823e-02971444652c)

**Describe alternatives you've considered**

**Additional context**

thx :-)

**Comment by roblatour** [comment]
Thanks for the ideas.

I doubt I’ll put the date (or time) on the screen, as the to make that info readable it would need to be relatively large (at least the size of the fonts used to show the power levels, which in turn would make such a small screen look rather cluttered.

Regarding the Bulk/Abs/Float – that would really only apply if the battery is near capacity otherwise bulk can be assumed.  Also, the little arrow that points up or down already indicates if the battery is being charged, discharged or has levelled out.

Regardless, the great thing about an open source project is that you can always branch the code and make whatever changes you like for yourself.
